### ISSUE TITLE
Amass requirement file Error

### ISSUE THREAD

**Issue by 007divyachawla** [ethicalhackingplayground/SubNuke#2]
amass_linux_amd64.zip                          100%[====================================================================================================>]  19.17M  3.66MB/s    in 17s     

2021-01-20 08:09:40 (1.14 MB/s) - ‘amass_linux_amd64.zip’ saved [20098092/20098092]

Archive:  amass_linux_amd64.zip
  inflating: amass_linux_amd64/LICENSE  
  inflating: amass_linux_amd64/README.md  
  inflating: amass_linux_amd64/doc/install.md  
  inflating: amass_linux_amd64/doc/scripting.md  
  inflating: amass_linux_amd64/doc/tutorial.md  
  inflating: amass_linux_amd64/doc/user_guide.md  
  inflating: amass_linux_amd64/examples/config.ini  
  inflating: amass_linux_amd64/examples/minimal.go  
  inflating: amass_linux_amd64/examples/wordlists/all.txt  
  inflating: amass_linux_amd64/examples/wordlists/bitquark_subdomains_top100K.txt  
  inflating: amass_linux_amd64/examples/wordlists/deepmagic.com_top500prefixes.txt  
  inflating: amass_linux_amd64/examples/wordlists/deepmagic.com_top50kprefixes.txt  
  inflating: amass_linux_amd64/examples/wordlists/fierce_hostlist.txt  
  inflating: amass_linux_amd64/examples/wordlists/jhaddix_all.txt  
  inflating: amass_linux_amd64/examples/wordlists/sorted_knock_dnsrecon_fierce_recon-ng.txt  
  inflating: amass_linux_amd64/examples/wordlists/subdomains-top1mil-110000.txt  
  inflating: amass_linux_amd64/examples/wordlists/subdomains-top1mil-20000.txt  
  inflating: amass_linux_amd64/examples/wordlists/subdomains-top1mil-5000.txt  
  inflating: amass_linux_amd64/examples/wordlists/subdomains.lst  
  inflating: amass_linux_amd64/amass  
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by 007divyachawla** [comment]
After running the command while installing the Amass it is givign this error.

**Comment by ethicalhackingplayground** [comment]
@007divyachawla Thank-you working on lot's of fixes today :) . There was a lot of code modifications to release it to public.
